### ISSUE TITLE
TypeError: Cannot read property 'fsPath' of undefined

### ISSUE THREAD

**Issue by Dirbaio** [tomoki1207/vscode-pdfviewer#62]
VSCode 1.44.2, Arch Linux

This happens with all PDFs when running the `View PDF` command.

```
[2020-04-21 19:28:55.835] [exthost] [error] TypeError: Cannot read property 'fsPath' of undefined
	at getPreviewTitle (/home/dirbaio/.vscode/extensions/tomoki1207.pdf-0.6.0/out/src/extension.js:84:30)
	at createPreview (/home/dirbaio/.vscode/extensions/tomoki1207.pdf-0.6.0/out/src/extension.js:78:62)
	at /home/dirbaio/.vscode/extensions/tomoki1207.pdf-0.6.0/out/src/extension.js:51:27
	at e._executeContributedCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:220)
	at e.$executeContributedCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:595)
	at e._doInvokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:683)
	at e._invokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:375)
	at e._receiveRequest (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:751:14)
	at e._receiveOneMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:749:832)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:748:34
	at e.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at v.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:206:615)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:919:744
	at e.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at v.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:206:615)
	at t.PersistentProtocol._receiveMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:211:17)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:208:155
	at e.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at p.acceptChunk (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:204:129)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:203:483
	at Socket.t (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:212:565)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) extension.pdf-preview
```

**Comment by tomoki1207** [comment]
That command is removed in v1.0.0.
Please try to show pdf like a text file, and reopen this issue if this problem still occurred.
